version: '3.7'
services:
    db:
      image: mysql
      restart: always
      ports:
        - "3306:3306"
      
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: appmysql
      volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/:ro
    django:
      restart: always
      build:
        context: .
      ports:
        - 8000:8000
      container_name: appmysql
      volumes:
        - .:/usr/src/app
      depends_on:
      - db
      command: >
        sh -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
