name: Myapp CI/CD
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: appmysql
        ports: ['3306:3306']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
      env: 
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: admin
          DBHOST: 127.0.0.1
          DBPORT: 3306
    - name: Run Tests
      run: |
        python manage.py test

      

        
      